language: java
#services:
#- docker
#cache:
#  directories:
#  - "$HOME/.m2"
jdk: openjdk8
#before_install:
#- chmod +x mvnw
install:
- mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true
after_success:
- bash <(curl -s https://codecov.io/bash)