---

matrix:
  include:
  -
    before_script:
    - "cd MockServer"
    jdk: openjdk8
    language: java
    script: "mvn clean package"
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  -
    before_script:
    - "cd codegenerator"
    jdk: openjdk8
    language: java
    script: "mvn clean package"
    after_success:
    - bash <(curl -s https://codecov.io/bash)

